### ISSUE TITLE
Minecraft 1.20.2 Support

### ISSUE THREAD

**Issue by FunnyShadow** [OKTW-Network/FabricProxy-Lite#64] opened 2023-10-06 03:23 UTC
Can Fabric Proxy Lite support 1.20.2? I have some servers that need to run on 1.20.2 fabric servers.

**Comment by gadget78** [comment] 2023-10-15 14:31
if you look at the "actions" tab .. 
so https://github.com/OKTW-Network/FabricProxy-Lite/actions
you can see a current build as been built, and can be tested.. 
sadly i haven't been able to connect in game with it this ? 
maybe it needs a more current version of velocity ?

**Comment by james58899** [comment] 2023-10-15 15:25
Velocity not yet support Minecraft 1.20.2 with FabricAPI, so I have not release a new version.

see https://github.com/PaperMC/Velocity/issues/1095 and https://github.com/PaperMC/Velocity/pull/1096

**Comment by gadget78** [comment] 2023-10-15 22:28
yeah seems to be having issues sadly, with everything else updated
i get error of `multiplayer.disconnect.missing_tags`
will have to wait for the fixes .. 

you think it maybe fixed via the FabricAPI ?

**Comment by srmullaney** [comment] 2023-10-18 02:16
Any updates on this? I am setting up a few servers for my friends and I and I need this to finish it all

**Comment by gadget78** [comment] 2023-10-19 16:55
> Velocity not yet support Minecraft 1.20.2 with FabricAPI, so I have not release a new version.
> 
> see [PaperMC/Velocity#1095](https://github.com/PaperMC/Velocity/issues/1095) and [PaperMC/Velocity#1096](https://github.com/PaperMC/Velocity/pull/1096)

i compiled your proposed PR/Fix and i can confirm it works :) Thankyou !!

**Comment by MrNavaStar** [comment] 2023-10-27 21:32
Velocity is now updated, a new release would be greatly appreciated!

**Comment by james58899** [comment] 2023-10-28 12:12
New version [v2.7.0](https://github.com/OKTW-Network/FabricProxy-Lite/releases/tag/v2.7.0) is released!

**Closed by james58899** 2023-10-28 12:12 UTC
